version: "3.2"
services:
    frontend:
      build: . 
      container_name: frontend
      ports:
        - 80:80
      networks:
        - frontend-network

networks:
  frontend-network:
    name: command_app_frontend-network
    external: true

